{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_sub():\n>       assert 1==2\nE       assert 1 == 2\n\nTestCases\\test_login.py:11: AssertionError"}, "start": 1685466120735, "stop": 1685466120735, "uuid": "119211c6-6f48-4b80-b1e3-7382776b7d36", "historyId": "963cd0d181bf4115f499e81877501557", "testCaseId": "963cd0d181bf4115f499e81877501557", "fullName": "TestCases.test_login#test_sub", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-2BK3DCT"}, {"name": "thread", "value": "21144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}