{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_sub():\n>       assert 1==2\nE       assert 1 == 2\n\nTestCases\\test_login.py:11: AssertionError"}, "start": 1685466041510, "stop": 1685466041510, "uuid": "1dbb1f17-47b8-4a3f-b181-139a510f520d", "historyId": "963cd0d181bf4115f499e81877501557", "testCaseId": "963cd0d181bf4115f499e81877501557", "fullName": "TestCases.test_login#test_sub", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-2BK3DCT"}, {"name": "thread", "value": "20416-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}